### ISSUE TITLE
Updating chromium notification after download hangs 

### ISSUE THREAD

**Issue by CarePackage17** [adolfintel/chromiumUpdater#15]
After downloading the notification says installing update indefinitely, even though it should launch the package installer as my phone is not rooted.

Device: bq aquaris X5
Android 6.0.1

**Comment by adolfintel** [comment]
After the download is complete, it has to extract the archive and it takes up to 1-2 minutes on slower phones. Did you try waiting for a bit before killing the app?

**Comment by CarePackage17** [comment]
That happens in the background anyway, doesn't it?
I just went back to the home screen after clicking update now; there doesn't seem to be a way to kill that process now.

It's been like this for hours already. As if it repeatedly tried to install but can't because the phone isn't rooted.

**Comment by adolfintel** [comment]
So basically it gets stuck in ChromiumUpdater.java between lines 203 an 232, but without getting any error, otherwise the indeterminate progress bar would go away.
I'll be honest, I have no idea what could possibly freeze during the extraction of a zip file. Do you want to try an APK with logging enabled so we can see what's going on?

**Comment by CarePackage17** [comment]
Sure. Do you provide debug binaries somewhere or do I need to build it myself?

**Comment by adolfintel** [comment]
Here:
[app-debug.zip](https://github.com/adolfintel/chromiumUpdater/files/1290630/app-debug.zip)

It will create a file in /sdcard/chrupd.log; run the application until you run into the issue, then kill the process and upload me that file.
